forecast/src/objects/ForecastHierarchyConfigurations__c.object
<CustomObject>
    <label>Forecast Hierarchy Configuration</label>
    <pluralLabel>Forecast Hierarchy Configurations</pluralLabel>
    <description>Forecast Hierarchy Configurations map a specific Role to a User that will act as a manager. Part of the Specialist Forecasting AppExchange package from Salesforce Labs.</description>
    <sharingModel>Private</sharingModel>
    <nameField>
        <displayFormat>FHC-{000000}</displayFormat>
        <label>Hierarchy Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <fields>
        <fullName>HierarchyRole__c</fullName>
        <label>Hierarchy Role</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HierarchyRoleUser__c</fullName>
        <label>Hierarchy Role User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>HierarchyRoleUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <label>Is Manager?</label>
        <defaultValue>true</defaultValue>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <label>Is Active?</label>
        <defaultValue>true</defaultValue>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

forecast/src/objects/SpecialistForecast__c.object
<CustomObject>
    <label>Specialist Forecast</label>
    <pluralLabel>Specialist Forecasts</pluralLabel>
    <description>Primary Custom Object for Specialist Forecasting that stores required info for each specialist forecast.</description>
    <sharingModel>Private</sharingModel>


    <nameField>
        <displayFormat>SAF-{00000000}</displayFormat>
        <label>Specialist Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>

    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SpecialistForecastToOpportunity</relationshipName>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>The Fiscal Year of the forecast record, which should always be set automatically.</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>The month the forecast belongs to, calculated from the Close Date.</inlineHelpText>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastCloseDate__c</fullName>
        <label>Close Date</label>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>Date the AE expects the opportunity to close.</inlineHelpText>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ForecastStage__c</fullName>
        <label>AE Opportunity Stage</label>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>Opportunity Stage chosen by the AE for the forecast.</inlineHelpText>
        <type>Picklist</type>
        <picklist>
            <picklistValues>
                <fullName>01 - Identifying an Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - Determining Problem, Impact, Ideal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - Validating Benefits &amp; Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - Confirming Value With Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - Negotiating &amp; Mutual Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - Finalizing Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Out Clause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - No Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - No Decision</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>ForecastCategory__c</fullName>
        <label>Forecast Category</label>
        <picklist>
            <controllingField>ForecastStage__c</controllingField>
            <picklistValues>
                <fullName>Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>Based on the Opportunity Stage, select a category the forecast apples to.</inlineHelpText>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastAmount__c</fullName>
        <required>true</required>
        <label>Opportunity Amount</label>
        <inlineHelpText>AE's forecast amount for his/her part of the opportunity.</inlineHelpText>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
    </fields>
</CustomObject>

forecast/src/classes/SpecForecastTestTrigger.cls
/*
Copyright (c) 2013, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE. Written by Michael Ball.
*/

/**
 *
 *  Description: Contains test cases to test utility methods for special forecast
 *  triggers.
 */

@isTest
public with sharing class SpecForecastTestTrigger {

    // Test Proper Insertion of a SpecialistForecast__c record
    private static testMethod void fcastInsert() {
        deleteAll();
        SpecialistForecast__c sfbad = new SpecialistForecast__c(
            ForecastAmount__c    = 100.00);
        try {
            INSERT sfbad;
            System.assert(false, 'Insert should not pass');
        } catch (Exception ex) {
            System.assert(true, 'Should have errors on insert of bad data');
        }
        Opportunity oppty = new Opportunity(
                     Name = 'Test Oppty',
                CloseDate = Date.newInstance(2013, 8, 16),
                StageName = 'Closed');
        INSERT oppty;
        SpecialistForecast__c sf = new SpecialistForecast__c(
            Opportunity__c       = oppty.Id,
            ForecastCategory__c  = 'Commit',
            ForecastCloseDate__c = Date.newinstance(2013, 08, 16),
            ForecastStage__c     = '06 - Finalizing Closure'
            );
        try {
            INSERT sf;
            System.assert(true, 'Insert should pass');
            // Trigger should automatically popular null data.
            System.assert(sf.ForecastAmount__c == 0);
            System.assert(sf.Month__c == 'August');
            // Could be FY12 or FY13 or FY14 depending on Org settings.
            System.assert(sf.FiscalYear__c != null);
        } catch (Exception ex) {
            System.assert(false, 'no errors on insert of good data');
        }
    }

    // Test proper insertion of a ForecastHierarchyConfigurations__c
    private static testMethod void hierarchyInsert() {
        deleteAll();
        ForecastHierarchyConfigurations__c fhcbad =
            new ForecastHierarchyConfigurations__c();
        try {
            INSERT fhcbad;
            System.assert(false, 'Insert should not pass');
        } catch (Exception ex) {
            System.assert(true, 'Should have errors on insert of bad data');
        }
        ForecastHierarchyConfigurations__c fhc =
            new ForecastHierarchyConfigurations__c(
                HierarchyRole__c = 'CEO',
                IsManager__c = true,
                IsActive__c = true,
                Comment__c = 'no comment',
                HierarchyRoleUser__c = UserInfo.getUserId()
                );
        try {
            INSERT fhc;
            System.assert(true, 'Insert should pass');
        } catch (Exception ex) {
            System.assert(false, 'no errors on insert of good data');
        }
    }

    /** Detele all forecast records and config items from org. */
    private static void deleteAll() {
        SpecialistForecast__c[] fcasts = [SELECT Id FROM SpecialistForecast__c];
        DELETE fcasts;
        ForecastHierarchyConfigurations__c[] fhc =
            [SELECT Id FROM ForecastHierarchyConfigurations__c];
        DELETE fhc;
    }
}