forecast/src/objects/SpecialistForecast__c.object
<CustomObject>
    <label>Specialist Forecast</label>
    <pluralLabel>Specialist Forecasts</pluralLabel>
    <description>Primary Custom Object for Specialist Forecasting that stores required info for each specialist forecast.</description>
    <sharingModel>Private</sharingModel>


    <nameField>
        <displayFormat>SAF-{00000000}</displayFormat>
        <label>Specialist Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>

    <fields>
        <fullName>FiscalYear__c</fullName>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>The Fiscal Year of the forecast record, which should always be set automatically.</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>The month the forecast belongs to, calculated from the Close Date.</inlineHelpText>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastCategory__c</fullName>
        <label>Forecast Category</label>
        <picklist>
            <controllingField>ForecastStage__c</controllingField>
            <picklistValues>
                <fullName>Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
        <inlineHelpText>Based on the Opportunity Stage, select a category the forecast apples to.</inlineHelpText>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastAmount__c</fullName>
        <required>true</required>
        <label>Opportunity Amount</label>
        <inlineHelpText>AE's forecast amount for his/her part of the opportunity.</inlineHelpText>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
        <description>Part of the Specialist Forecasting Unmanaged Package from Salesforce Labs</description>
    </fields>
    <fields>
        <fullName>ExcludeFromCalculation__c</fullName>
        <label>Exclude From Calculation?</label>
        <defaultValue>false</defaultValue>
        <type>Checkbox</type>
    </fields>
</CustomObject>

forecast/src/classes/ForecastIterable.cls
/*
Copyright (c) 2013, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE. Written by Michael Ball.
*/

/**
 * Custom Iterator for Specialist Forecast Batch Job
 *
 */
global with sharing class ForecastIterable implements Iterator<AggregateResult> {

    global Integer count { get;set; }
    global AggregateResult[] ownerMap { get;set; }

    global ForecastIterable() {
        count = 0;
        ownerMap = [SELECT OwnerId,
                           ForecastCategory__c,
                           FiscalYear__c,
                           Month__c,
                    SUM(ForecastAmount__c) amnt
                    FROM SpecialistForecast__c
                    WHERE ExcludeFromCalculation__c != true
                    GROUP By OwnerId,
                             ForecastCategory__c,
                             FiscalYear__c,
                             Month__c
                    ORDER by OwnerID,
                             FiscalYear__c,
                             Month__c];
    }

    global boolean hasNext() {
        return count < ownerMap.size();
    }

    global AggregateResult next() {
        return ownerMap[count++];
    }

}