forecast/sfdc/src/objects/SpecialistForecast__c.object
<CustomObject>
    <label>Specialist Forecast Objects List</label>
    <pluralLabel>Specialist Forecasts</pluralLabel>
    <description>Primary Custom Object for Specialist Forecasting</description>
    <sharingModel>Private</sharingModel>


    <nameField>
        <displayFormat>SAF-{00000000}</displayFormat>
        <label>Specialist Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>

    <fields>
        <fullName>FiscalYear__c</fullName>
        <inlineHelpText>The Fiscal Year of the forecast record</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastStatus__c</fullName>
        <!-- <required>true</required> FIXME -->
        <label>Forecast Category</label>
        <picklist>
            <controllingField>ForecastStage__c</controllingField>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastAmount__c</fullName>
        <label>AE Opportunity Amount</label>
        <inlineHelpText>AE's forecast amount for his/her part of the opportunity.</inlineHelpText>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
        <description>AE's forecast amount for his/her part of the opportunity.s</description>
    </fields>
    <fields>
        <fullName>ExcludeFromCalculation__c</fullName>
        <label>Exclude From Calculation?</label>
        <defaultValue>false</defaultValue>
        <type>Checkbox</type>
    </fields>


</CustomObject>

forecast/sfdc/src/classes/ForecastIterable.cls
/**
 * Custom Iterator for Specialist Forecast Batch Job
 *
 * @author auzzaman
 * @since 180.store
 */
global with sharing class ForecastIterable implements Iterator<AggregateResult> {

    global Integer count {get; set;}
    global AggregateResult[] ownerMap {get; set;}

    global ForecastIterable() {
        count = 0;
//      List<String> supportFYs = ForecastHelper.getSupportedFiscalYearsForForecast();
        ownerMap = [SELECT OwnerId, ForecastStatus__c, FiscalYear__c, FYMonth__c,
                     SUM(ForecastAmount__c) amnt FROM SpecialistForecast__c
                    WHERE  ExcludeFROMCalculation__c != true Group By OwnerId,
                    ForecastStatus__c, FiscalYear__c, FYMonth__c Order by OwnerID,
                    FiscalYear__c, FYMonth__c];
    }

    global boolean hasNext() {
        return count < ownerMap.size();

//       if(count >= ownerMap.size()) {
//             return false;
//         } else {
//             return true;
//         }
    }

    global AggregateResult next() {
        return ownerMap[count++];
    }

}