forecast/sfdc/src/objects/SpecialistForecast__c.object
<CustomObject>
    <label>Specialist Forecast Objects List</label>
    <pluralLabel>Specialist Forecasts</pluralLabel>
    <description>Primary Custom Object for Specialist Forecasting</description>
    <sharingModel>Private</sharingModel>


    <nameField>
        <displayFormat>SAF-{00000000}</displayFormat>
        <label>Specialist Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>

    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <formula>
            Opportunity__r.Account.Name &amp; ' - ' &amp; 'https://login.salesforce.com/' &amp; Opportunity__r.Account.Id
        </formula>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SpecialistForecastToOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <inlineHelpText>The Fiscal Year of the forecast record</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastCloseDate__c</fullName>
        <label>Close Date</label>
        <inlineHelpText>Date the AE expects the opportunity to close</inlineHelpText>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ForecastStage__c</fullName>
        <label>AE Forecast Stage</label>
        <!-- <required>true</required> -->
        <inlineHelpText>Opportunity Stage chosen by the AE for the forecast.</inlineHelpText>
        <type>Picklist</type>
        <picklist>
            <picklistValues>
                <fullName>01 - Identifying an Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02 - Determining Problem, Impact, Ideal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03 - Validating Benefits &amp; Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04 - Confirming Value With Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05 - Negotiating &amp; Mutual Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06 - Finalizing Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07 - Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08 - Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Out Clause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - No Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead - No Decision</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>ForecastStatus__c</fullName>
        <!-- <required>true</required> FIXME -->
        <label>Forecast Category</label>
        <picklist>
            <controllingField>ForecastStage__c</controllingField>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastAmount__c</fullName>
        <label>AE Opportunity Amount</label>
        <inlineHelpText>AE's forecast amount for his/her part of the opportunity.</inlineHelpText>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
        <description>AE's forecast amount for his/her part of the opportunity.s</description>
    </fields>


</CustomObject>

forecast/sfdc/src/classes/SplstForecastDrildownOptyController.cls
/*
Copyright (c) 2013, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE. Written by Michael Ball.
*/

/**
 *
 *
 */
public with sharing class SplstForecastDrildownOptyController {

    public List<SpecialistForecast__c> specialistforecastList{get;set;}

    private static final String CLOSED = ForecastHelper.CLOSED;
    private static final String CLOSED_WON = ForecastHelper.CLOSED_WON;


    /**********Constructor***********/
    public SplstForecastDrildownOptyController() {
         String SelectedFQ = System.currentPageReference().getParameters().get('fq');
         String SelectedFY = System.currentPageReference().getParameters().get('fy');
         Id SelectedOwner = System.currentPageReference().getParameters().get('oId');
         String status = System.currentPageReference().getParameters().get('st');

         selectedFQ = SelectedFQ != null ?
             String.escapeSingleQuotes(SelectedFQ) : null;
         selectedFY = SelectedFY != null ?
             String.escapeSingleQuotes(SelectedFY) : null;
         selectedOwner = SelectedOwner != null ?
             String.escapeSingleQuotes(SelectedOwner) : null;
         status = status != null ? String.escapeSingleQuotes(status) : null;

         List<String> lstStatus = new List<String>();
         lstStatus.add(status);
         if (status == CLOSED) {
             lstStatus.add(CLOSED_WON);
         }
         if (SelectedFQ != null && SelectedFY != null&& SelectedOwner != null ) {
                 this.getSpecialistForecastRecords(SelectedFY, SelectedFQ,
                     SelectedOwner,lststatus);
         }
    }

    public void getSpecialistForecastRecords(String fy, String fq, Id ownerId, 
    String[] lststatus) {
        //get months by quarter
        List<String> lstMonths = ForecastHelper.getMonthsInQuarter(fq);
        specialistforecastList=[SELECT Opportunity__C,Opportunity__r.Name,
                                    Account__c, FiscalYear__c, FYMonth__c,
                                    ForecastAmount__c, ForecastStatus__c,
                                    ForecastCloseDate__c, ForecastStage__c
                                    FROM SpecialistForecast__c
                                    WHERE FiscalYear__c = :fy
                                    AND FYMonth__c in :lstMonths
                                    AND OwnerId = :ownerId
                                    AND ForecastStatus__c in :lststatus];
    }
}