forecast/sfdc/src/objects/SpecialistForecastLineItem__c.object
<CustomObject>
    <label>Specialist Forecast Line Item</label>
    <pluralLabel>Specialist Forecast Line Items</pluralLabel>
    <description>Specialist Forecast Line Items within 62 Org</description>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>ExtIdentifier__c</fullName>
        <externalId>true</externalId>
        <label>External Identifier</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FYMonth__c</fullName>
        <inlineHelpText>The month in number for the year starting from 1</inlineHelpText>
        <label>FY Month #</label>
        <picklist>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <inlineHelpText>Returns the FY of the record</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forecast Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SpecialistForecastLineItemToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>SpecialistForecastOverride__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialist Forecast Override</label>
        <referenceTo>SpecialistForecastOverride__c</referenceTo>
        <relationshipName>SpecialistForecastLineItemToOverride</relationshipName>
        <type>Lookup</type>
    </fields>

    <nameField>
        <displayFormat>SFL-{00000000}</displayFormat>
        <label>Specialist Forecast Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    
</CustomObject>

forecast/sfdc/src/objects/SpecialistForecastOverride__c.object
<CustomObject>
    <label>Specialist Forecast Override</label>
    <pluralLabel>Specialist Forecast Overrides</pluralLabel>
    <description>Specialist Forecast Overrides within 62 Org</description>
    <sharingModel>Private</sharingModel>


    <nameField>
    <displayFormat>SFO-{00000000}</displayFormat>
    <label>Specialist Forecast Override</label>
    <type>AutoNumber</type>
    </nameField>

     <fields>
    <fullName>OwnOverrideNotes__c</fullName>
    <label>Own Override Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
    </fields>
    <fields>
    <fullName>ManagerOverrideCommitNotes__c</fullName>
    <label>Manager Override Commit  Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
    </fields>
    <fields>
    <fullName>ManagerOverrideBestCaseNotes__c</fullName>
    <label>Manager Override best case Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
    </fields>
    <fields>
    <fullName>PreviousDirectRepCommitAmount__c</fullName>
    <label>Previous Commit Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Old Direct Report Commit forecasted opportunity  total amount for cloud-specific products</description>
    </fields>
    <fields>
        <fullName>PreviousDirectRepBestcaseAmount__c</fullName>
        <label>Previous Bestcase Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
        <description>Old Direct Report Bestcase forecasted opportunity  total amount for cloud-specific products</description>
    </fields>
   <fields>
    <fullName>PeriodType__c</fullName>
    <label>Period Type</label>
        <length>20</length>
    <type>Text</type>
    <description>PeriodType (values Could be Month Name(June, July etc..)  or Q1,Q2, etc depending upon the values</description>
    </fields>
     <fields>
        <fullName>ExtIdentifier__c</fullName>
        <externalId>true</externalId>
        <label>External Identifier</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

    
</CustomObject>

forecast/sfdc/src/classes/SpecialistForecastOverrideController.cls
/**
 * Controller Class used for Specialist Forecast override popup page
 *
 * @author smohapatra
 * @since 180.store
 */
public with sharing class SpecialistForecastOverrideController {

    public Decimal overrideAmount{get;set;}
    public Decimal originalAmount{get;set;}
    public Decimal originaloldAmount{get;set;}
    public String overrideComment{get;set;}
    public String strRecordId {get;set;}
    public String strField {get;set;}
    public boolean pageRefresh{get;set;}
    public String lineItemownerID {get;set;}
    public String strFY {get;set;}
    public String strFQ {get;set;}

    //Constructor
    public SpecialistForecastOverrideController () {
        /* if(System.currentPageReference().getParameters().get('token')!=null)
            {
         String temp = EncodingUtil.base64Decode(System.currentPageReference().getParameters().get('token')).toString();

         originalAmount = decimal.valueOf(temp);
         //originalAmount = decimal.valueOf(System.currentPageReference().getParameters().get('token'));
            }
        */
        String temp = System.currentPageReference().getParameters().get('Amt');

        if (temp != null) {
            temp = String.escapeSingleQuotes(temp);

            try {
                  originalAmount = decimal.valueOf(temp);
            } catch (Exception ex) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Invalid Override Amount'));
            }
        }

        String oldamt = System.currentPageReference().getParameters().get('orgamt');

        if (oldamt != null) {
            oldamt = String.escapeSingleQuotes(oldamt);

            try {
                originaloldAmount = decimal.valueOf(oldamt);
            } catch (Exception ex) {

            }
        }

        strRecordId = System.currentPageReference().getParameters().get('RecId');

        if (strRecordId != null) {
            strRecordId = String.escapeSingleQuotes(strRecordId );
        }
        strField = System.currentPageReference().getParameters().get('field');
        if (strField != null) {
            strField = String.escapeSingleQuotes(strField);
        }
        lineItemownerID = System.currentPageReference().getParameters().get('ownerId');
        if (lineItemownerID != null) {
            lineItemownerID = String.escapeSingleQuotes(lineItemownerID );
        }
        strFQ = System.currentPageReference().getParameters().get('fq');
        if (strFQ != null) {
            strFQ = String.escapeSingleQuotes(strFQ);
        }
       strFY = System.currentPageReference().getParameters().get('fy');
       if (strFY != null) {
           strFY = String.escapeSingleQuotes(strFY);
       }
    }

     public pagereference saveOverride() {

        SpecialistForecastLineItem__c spc = new SpecialistForecastLineItem__c();
        SpecialistForecastOverride__c spovr = new SpecialistForecastOverride__c();
        String external_Key;
        if (strField == 'mycommit') {

            if (isSelfOverride()) {
                spovr.OwnOverridenCommitAmount__c = overrideAmount;
                spovr.OwnOverrideNotes__c = overridecomment;
            } else {
                spovr.ManagerOverridenCommitAmount__c = overrideAmount;
                spovr.ManagerOverrideCommitNotes__c = overridecomment;

            }
            spovr.PreviousDirectRepCommitAmount__c = originaloldAmount;
        }else if(strField =='mybestcase'){

             if(isSelfOverride()){
                spovr.OwnOverridenBestCaseAmount__c = overrideAmount;
                spovr.OwnOverrideNotes__c = overrideComment;
            }else{
                spovr.ManagerOverridenBestCaseAmount__c = overrideAmount;
                spovr.ManagerOverrideBestcaseNotes__c = overrideComment;

            }
           spovr.PreviousDirectRepBestcaseAmount__c = originaloldAmount;
        }
        spovr.PeriodType__c = strFQ;
        external_Key = lineItemownerID + strFY + strFQ;
        spovr.ExtIdentifier__c = external_Key;
        spovr.OwnerId = lineItemownerID;

        try{
            Upsert spovr ExtIdentifier__c;
         }catch(System.DMLException ex){

             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,' Failed to update the Override value'));
            return null;
        }

        //upsert Line item
        List<String> lstMonths = ForecastHelper.getMonthsInQuarter(strFQ);

        spc.ExtIdentifier__c = lineItemownerID + strFY + lstMonths.get(0);
        spc.SpecialistForecastOverride__c = spovr.Id;
        spc.FYMonth__c = lstMonths.get(0);
        spc.ForecastOwner__c = lineItemownerID;
        spc.FiscalYear__c = strFY;
        spc.OwnerId = lineItemownerID;
        try {
            Upsert spc ExtIdentifier__c;
         } catch(System.DMLException ex) {
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,' Failed to update the Override Amount'));
             return null;
        }

        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Override Amount updated sucessfully'));
        return null;
     }

     private boolean isSelfOverride(){
         Boolean blnoverride = false;
         if (UserInfo.getUserId() == lineItemownerID){
             blnoverride = true;
         }
         return blnoverride;
     }
}