forecast/sfdc/src/objects/SpecialistForecastLineItem__c.object
<CustomObject>
    <label>Specialist Forecast Line Item</label>
    <pluralLabel>Specialist Forecast Line Items</pluralLabel>
    <description>Specialist Forecast Line Items within 62 Org</description>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>ExtIdentifier__c</fullName>
        <externalId>true</externalId>
        <label>External Identifier</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FYMonth__c</fullName>
        <inlineHelpText>The month in number for the year starting from 1</inlineHelpText>
        <label>FY Month #</label>
        <picklist>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FiscalYear__c</fullName>
        <inlineHelpText>Returns the FY of the record</inlineHelpText>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>FY11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FY16</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ForecastOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forecast Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SpecialistForecastLineItemToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginalBestCaseAmount__c</fullName>
        <description>Specialist AE&apos;s forecasted opportunity best case amount for their cloud-specific products</description>
        <label>Original Best Case Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriginalClosedAmount__c</fullName>
        <description>Specialist AE&apos;s forecasted opportunity closed amount for their cloud-specific products</description>
        <label>Original Closed Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriginalCommitAmount__c</fullName>
        <description>Specialist AE&apos;s forecasted opportunity commit amount for their cloud-specific products</description>
        <label>Original Commit Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriginalPipelineAmount__c</fullName>
        <description>Specialist AE&apos;s forecasted opportunity pipeline amount for their cloud-specific products</description>
        <label>Original Pipeline Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    

    <nameField>
        <displayFormat>SFL-{00000000}</displayFormat>
        <label>Specialist Forecast Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    
</CustomObject>

forecast/sfdc/src/classes/SpecialistForecastBatch.cls
/**
 * Batch job for processing Specialist Forecast amounts to Specialist Forecast Reports
 *
 * To Run this Class from the Console:
 *
 * @author auzzaman,smohapatra
 * @since 180.store
 */

global with sharing class SpecialistForecastBatch implements
    Database.Batchable<AggregateResult> {

    global Map<String, AggregateResult[]> input {get; set;}
    global Map<String, SpecialistForecastLineItem__c> processedRecords {get; set;}
    public DateTime starttime = System.now();
    public Boolean isRunningByUser = false;

    /**
     *
     * @return TODO
     */
    global Iterable<AggregateResult> start(Database.BatchableContext context) {
        /* FIXME: Remove before prod! */
        System.debug('Start SpecialistForecastBatch ' + System.now());
        return new ForecastCollection();
    }

    /**
     * Send error email notification to the gack email
     * @param String subject
     * @param String formattedBody
     */
    private static void sendErrorNotification(String subject,
    String formattedBody, String gackEmailIds) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[]{gackEmailIds});
        mail.setSubject(subject);
        mail.setPlainTextBody(formattedBody);

        try {
            Messaging.sendEmail(new Messaging.Email[] { mail });
            // Messaging.sendSystemEmail(mail, 'do-not-reply@salesforce.com');
        } catch(System.Exception ex) {
            /* FIXME: Remove before prod!! */
            System.debug('Error in sendMail ' + ex.getMessage());
        }
    }

    /**
     *
     * @return TODO
     */
    global void execute(Database.BatchableContext context, List<Sobject> items) {
        /* FIXME: Remove before prod! */
        System.debug('Running SpecialistForecastBatch ' + System.now());
        /* FIXME: Remove before prod! */
        System.debug('items.size() = ' + items.size());
        // upsert to SpecialistForecastLineItem  based on input map.
        List<SpecialistForecastLineItem__c> allLineItems = new
            List<SpecialistForecastLineItem__c>();

        SpecialistForecastLineItem__c item;
        processedRecords = new Map<String, SpecialistForecastLineItem__c>();

        String previousKey;
        String temp;
        String external_Key;

        for (Sobject so : items)  {
            AggregateResult ar = (AggregateResult) so;
            // process the results
            external_Key = (String) ar.get('OwnerId') +
                (String) ar.get('FiscalYear__c') + (String) ar.get('FYMonth__c');
            if (processedRecords.get(external_Key) == null) {
                 item = new SpecialistForecastLineItem__c();
                 item.OriginalClosedAmount__c   = 0;
                 item.OriginalBestCaseAmount__c = 0;
                 item.OriginalPipelineAmount__c = 0;
                 item.OriginalCommitAmount__c   = 0;
                 processedRecords.put(external_Key, item);
             }

            item = processedRecords.get(external_Key);
            item.ForecastOwner__c = (Id) ar.get('OwnerId');
            item.OwnerId = (Id) ar.get('OwnerId');
            item.FiscalYear__c = (String)ar.get('FiscalYear__c');
            temp = (String) ar.get('FYMonth__c');
            item.FYMonth__c =  temp;
            temp = (String) ar.get('ForecastStatus__c');
            Decimal tempAmount = (Decimal) ar.get('amnt');

            if (temp == 'Closed Won' || temp == 'Closed' ) {
                item.OriginalClosedAmount__c = tempAmount;
            } else  if(temp == 'Commit') {
                item.OriginalCommitAmount__c = tempAmount;
            } else  if(temp == 'Best Case') {
                item.OriginalBestCaseAmount__c = tempAmount;
            } else  if(temp == 'Pipeline') {
                item.OriginalPipelineAmount__c = tempAmount;
            }

            item.ExtIdentifier__c = external_Key;
            /* FIXME: Remove before prod! */
            System.debug(item + 'externalkey' + external_Key);

            processedRecords.put(external_Key,item);
            //check if
            if (previousKey != external_Key){
                previousKey = external_Key;
                allLineItems.add(item);
            }
        }


        /* FIXME: Remove before prod! */
        System.debug('1. processedRecords.size() = ' + processedRecords.size());
        /* FIXME: Remove before prod! */
        System.debug('2. allLineItems.size() = ' + allLineItems.size());

        // now upsert at one shot
        try {
            Schema.SObjectField fld = SpecialistForecastLineItem__c.Fields.ExtIdentifier__c;
            Database.upsert(allLineItems, fld, false);

        } catch(DMLException e) {
            String email = ForecastHelper.getCronEmail();
            if(email != ForecastHelper.DO_NOT_SEND_EMAIL) {
                sendErrorNotification('Error in the Specialist Forecast Batch Process',
                    'Specialist Forecast Batch Process not completed Successfully'
                        + e.getMessage(), email);
            }
            /* FIXME: Remove before prod! */
            System.debug(e.getMessage());
        }
    }

    /**
     *
     * @return TODO
     */
    global void finish(Database.BatchableContext context) {
        /* FIXME: Remove before prod! */
        System.debug('Finish SpecialistForecastBatch ' + System.now());
        updateSFLineItems();
        String email = ForecastHelper.getCronEmail();
        User usr = [SELECT EMail FROM User WHERE Id=:UserInfo.getUserId() limit 1];
        if (isRunningByUser) {
            email = usr.EMail;
        }


        if (email != ForecastHelper.DO_NOT_SEND_EMAIL) {
            sendErrorNotification('SpecialistForecastBatch Process Completed',
                'Specialist Forecast Batch Process has completed', email);
        }

    }

    /*
     * update all the line items amount to 0 those are not updated by
     * current process
     */
    private void updateSFLineItems(){
        List<SpecialistForecastLineItem__c> spllist = [SELECT Id,
                            OriginalPipelineAmount__c, OriginalClosedAmount__c,
                            OriginalBestCaseAmount__c, OriginalCommitAmount__c
                            FROM SpecialistForecastLineItem__c
                            WHERE LastModifiedDate < :starttime];

        for (SpecialistForecastLineItem__c item : spllist) {
              item.OriginalClosedAmount__c   = 0;
              item.OriginalCommitAmount__c   = 0;
              item.OriginalBestCaseAmount__c = 0;
              item.OriginalPipelineAmount__c = 0;
        }
         // TODO- store the update() in UpdateResult[] and log the error messages if any record failed update.
         Database.update(spllist,false);



    }
}